spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:address-book.db
  jpa:
    database-platform: com.example.addressbook.dialect.SqliteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    web:
      pageable:
        default-page-size: 10
        page-parameter: number
springdoc:
  swagger-ui:
    path: /swagger-ui.html